"""create quotes and price catalog tables

Revision ID: 155aad4a96e6
Revises: ce4a1623fcbf
Create Date: 2026-09-01 00:12:13.675063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '155aad4a96e6'
down_revision: Union[str, Sequence[str], None] = 'ce4a1623fcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recurring_price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recurring_price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recurring_label', sa.String(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'aceptada', 'rechazada', name='quote_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_business', sa.String(), nullable=True),
    sa.Column('client_contact', sa.String(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recurring_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('price_catalog_items')
    # ### end Alembic commands ###
